<?php
require_once('../../../vendor2/vendor/tecnickcom/tcpdf/tcpdf.php');

if (isset($_POST['generate_pdf'])) {
    $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
    $pdf->SetTitle('Invoice Pesanan');
    $pdf->AddPage();
    $bootstrap_css = 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css';
    $bootstrap_js = 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js';
    $html = '<head>';
    $html .= '<link href="' . $bootstrap_css . '" rel="stylesheet">';
    $html .= '<script src="' . $bootstrap_js . '" crossorigin="anonymous"></script>';
    $html .= '</head>';
    $html .= '<body>';
    $html .= '<div class="container-fluid px-5">';
    $html .= '<div class="row justify-content-between mb-5">';
    $html .= '<div class="col-md-2 stamp-logo">';
    $html .= '<img src="../assets/img/Logo PTSP1.png" class="img-fluid" alt=""
    style="background-color: #e2e3e5; margin: 0 0 0 80px; padding: 70px 10px 10px 10px; border-radius: 0 0 10px 10px;">';
    $html .= '<div class="container-fluid px-5">';
    $html .= '<h3 class="text-center fw-bold">Invoice Pesanan</h3>';
    $html .= '<hr>';
    $html .= '<div class="row justify-content-between mb-5">';
    $html .= '<div class="col-md-2 stamp-logo">';
    $html .= '<img src="./Logo PTSP1.png" class="img-fluid" alt="" style="background-color: #e2e3e5; margin: 0 0 0 80px; padding: 70px 10px 10px 10px; border-radius: 0 0 10px 10px;">';
    $html .= '</div>';
    $html .= '<div class="col-md-4 text-center header-invoice" style="padding: 70px 10px 10px 10px;">';
    $html .= '<h3 class="title fw-bold">INFORMASI PESANAN</h3>';
    $html .= '<h4>No Pesanan #35426582362387</h4>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '<div class="row justify-content-between mb-3">';
    $html .= '<div class="col-md-4 mt-4">';
    $html .= '<h5 class="fw-bold">PENERIMA INSTANSI A (No.Rekening 1111)</h5>';
    $html .= '</div>';
    $html .= '<div class="col-md-2 mt-4 text-center status-invoice" style="color: white; background: #db0000; backdrop-filter: blur(3px); -webkit-backdrop-filter: blur(3px); border-radius: 10px; border: 1px solid rgba(255, 255, 255, 0.18);">';
    $html .= '<span class="align-middle"><strong class="">Status Pesanan : Belum Lunas</strong></span>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '<table id="tabelTransaksiA" class="table mb-4">';
    $html .= '<thead class="table-secondary">';
    $html .= '<tr>';
    $html .= '<td>Produk</td>';
    $html .= '<td>Rekening</td>';
    $html .= '<td>Harga</td>';
    $html .= '<td>Jumlah</td>';
    $html .= '<td>Total</td>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td class="produk ps-3">Jasa 1</td>';
    $html .= '<td class="rekening ps-3">1111</td>';
    $html .= '<td class="harga ps-3">Rp 100.000</td>';
    $html .= '<td class="jumlah ps-3">2</td>';
    $html .= '<td class="total ps-3">Rp 200.000</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '</table>';
    $html .= '<div class="row justify-content-between mb-3">';
    $html .= '<div class="col-md-4 mt-4">';
    $html .= '<h5 class="fw-bold">PENERIMA INSTANSI B (No.Rekening 2222)</h5>';
    $html .= '</div>';
    $html .= '<div class="col-md-2 mt-4 text-center status-invoice" style="color: white; background: #db0000; backdrop-filter: blur(3px); -webkit-backdrop-filter: blur(3px); border-radius: 10px; border: 1px solid rgba(255, 255, 255, 0.18);">';
    $html .= '<span class="align-middle"><strong class="">Status Pesanan : Belum Lunas</strong></span>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '<table id="tabelTransaksiB" class="table mb-4">';
    $html .= '<thead class="table-secondary">';
    $html .= '<tr>';
    $html .= '<td>Produk</td>';
    $html .= '<td>Rekening</td>';
    $html .= '<td>Harga</td>';
    $html .= '<td>Jumlah</td>';
    $html .= '<td>Total</td>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td class="produk ps-3">Informasi 2</td>';
    $html .= '<td class="rekening ps-3">1111</td>';
    $html .= '<td class="harga ps-3">Rp 100.000</td>';
    $html .= '<td class="jumlah ps-3">2</td>';
    $html .= '<td class="total ps-3">Rp 200.000</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '</table>';
    $html .= '<div class="row justify-content-between mb-3">';
    $html .= '<div class="col-md-4 mt-4">';
    $html .= '<h5 class="fw-bold">PENERIMA INSTANSI C (No.Rekening 3333)</h5>';
    $html .= '</div>';
    $html .= '<div class="col-md-2 mt-4 text-center status-invoice" style="color: white; background: #db0000; backdrop-filter: blur(3px); -webkit-backdrop-filter: blur(3px); border-radius: 10px; border: 1px solid rgba(255, 255, 255, 0.18);">';
    $html .= '<span class="align-middle"><strong class="">Status Pesanan : Belum Lunas</strong></span>';
    $html .= '</div>';
    $html .= '</div>';
    $html .= '<table id="tabelTransaksiC" class="table mb-4">';
    $html .= '<thead class="table-secondary">';
    $html .= '<tr>';
    $html .= '<td>Produk</td>';
    $html .= '<td>Rekening</td>';
    $html .= '<td>Harga</td>';
    $html .= '<td>Jumlah</td>';
    $html .= '<td>Total</td>';
    $html .= '</tr>';
    $html .= '</thead>';
    $html .= '<tbody>';
    $html .= '<tr>';
    $html .= '<td class="produk ps-3">Informasi 3</td>';
    $html .= '<td class="rekening ps-3">1111</td>';
    $html .= '<td class="harga ps-3">Rp 100.000</td>';
    $html .= '<td class="jumlah ps-3">2</td>';
    $html .= '<td class="total ps-3">Rp 200.000</td>';
    $html .= '</tr>';
    $html .= '</tbody>';
    $html .= '</table>';
    $html .= '</div>';
    $html .= '</body>';
    $pdf->writeHTML($html, true, false, true, false, '');
    $pdf->Output('invoice_pesanan.pdf', 'D');
}
